id: I2A4664F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T12:56:08+00:00'
last_modified: '2022-06-08T14:26:52.276068+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS60373
  title: བོད་ལུགས་གསོ་རིག་དཔེ་རྙིང་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    649F:
      image_group_id: I1GS60375
      title: ''
      total_pages: 460
      order: 1
      base_file: 649F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
