id: P010553
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-19 20:55:41.007562
source_metadata:
  id: bdr:W1GS60373
  title: བོད་ལུགས་གསོ་རིག་དཔེ་རྙིང་དཀར་ཆག
  author: ''
  volumes:
    981c62c3538541d5bb10b8ab6a0c68eb:
      image_group_id: I1GS60375
      title: ''
      volume_number: 1
      total_pages: 460
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
